sudo: required
services:
  - docker

before_install:
  - docker build -t anasabdullah/docker-react -f Dockerfile.dev .

script:
  - docker run anasabdullah/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "test-app"
  env: "TestApp-env"
  bucket_name: "elasticbeanstalk-us-east-1-506338780946"
  bucket_path: "test-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"